# Generated by Django 3.0.7 on 2020-07-29 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_users_email_verified'),
        ('reviews', '0002_auto_20200727_0548'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Users'),
        ),
    ]
