# Generated by Django 3.0.7 on 2020-07-26 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'genre_category',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.TextField(max_length=1000)),
            ],
            options={
                'db_table': 'image',
            },
        ),
        migrations.CreateModel(
            name='Line_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'line_category',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'menus',
            },
        ),
        migrations.CreateModel(
            name='Online_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Menu')),
            ],
            options={
                'db_table': 'online_category',
            },
        ),
        migrations.CreateModel(
            name='Product_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, null=True)),
                ('updated', models.DateField(auto_now=True, null=True)),
                ('tag', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('price_sale', models.IntegerField()),
                ('detail_html', models.TextField(max_length=1000)),
            ],
            options={
                'db_table': 'product_detail',
            },
        ),
        migrations.CreateModel(
            name='Product_Plag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag_sale', models.CharField(max_length=10)),
                ('flag_gift', models.CharField(max_length=10)),
                ('flag_new', models.CharField(max_length=10)),
                ('flag_best', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'product_flag',
            },
        ),
        migrations.CreateModel(
            name='Product_Star',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star_5', models.IntegerField(default=0)),
                ('star_4', models.IntegerField(default=0)),
                ('star_3', models.IntegerField(default=0)),
                ('star_2', models.IntegerField(default=0)),
                ('star_1', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'product_star',
            },
        ),
        migrations.CreateModel(
            name='Skin_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Menu')),
            ],
            options={
                'db_table': 'skin_category',
            },
        ),
        migrations.CreateModel(
            name='Product_Detail_Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Image')),
                ('product_detail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Product_Detail')),
            ],
            options={
                'db_table': 'product_detail_image',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, null=True)),
                ('updated', models.DateField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('main_image_url', models.CharField(default='', max_length=1000)),
                ('is_main', models.BooleanField(default=False)),
                ('flag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Product_Plag')),
                ('genre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Genre_Category')),
                ('line', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Line_Category')),
                ('online', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Online_Category')),
                ('product_detail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Product_Detail')),
                ('skin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Skin_Category')),
                ('star', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Product_Star')),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.AddField(
            model_name='line_category',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Menu'),
        ),
        migrations.AddField(
            model_name='genre_category',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Menu'),
        ),
        migrations.CreateModel(
            name='Distinct_Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, null=True)),
                ('updated', models.DateField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('flag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Product_Plag')),
                ('genre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Genre_Category')),
                ('line', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Line_Category')),
                ('online', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Online_Category')),
                ('skin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Skin_Category')),
                ('star', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Product_Star')),
            ],
            options={
                'db_table': 'non_products',
            },
        ),
    ]
